### ISSUE TITLE
Indeksowanie stron

### ISSUE THREAD

**Issue by patrys666** [nokaut/white-label-demo#22]
Czy to normalne, że google mimo wygenerowanej i przesłanej mapy witryny nie chce zaindeksować tych stron? Na początku miałem zaindeksowane ponad 50k stron, teraz ta liczba spadła do kilku.

**Comment by dwilkiewicz** [comment]
Od dłuższego czasu obserwujemy na wielu stronach problemy z indeksowaniem, szczególnie jeśli Google nie widzi wartości na stronie dla użytkownika lub strona ma niskie wyniki w testach wydajności (https://pagespeed.web.dev/). Poza tym ograniczany jest budżet Google dla stron na indeksowanie, Google ma spore problemy techniczne z czytaniem całego internetu.
