### ISSUE TITLE
Problemy z PHP 7

### ISSUE THREAD

**Issue by jcobk** [nokaut/white-label-demo#7]
Nie wiem jeszcze dlaczego, ale jest problem z działaniem WL pod PHP 7 - zostawiam info, żeby nie zaginęło. Może sam będę miał trochę czasu żeby na to bliżej spojrzeć i poprawię.

Problem - co któreś odświeżenie np. strony kategorii (CategoryController/index)
```php
$products = $productsFetch->getResult();
```

zamiast listy produktów zwraca NULLa, co powoduje wysypanie się strony.

Może (ale nie musi ;)) to być związane z implementacją cURLa albo Memcached (zmieniłem Memcache->Memcached) dla PHP7.

Kiedy przepiąłem WL na PHP 5.6 (ale zostawiając Memcached) problem przestał występować.

**Comment by jjuszkiewicz** [comment]
Znamy ten problemie, występuje on w PHP 7.0 pod php-fpm (pod php-cli nie występuje). Problem jest z wyciąganiem danych z memcached. JSON który jest zapisywany do cache po wyciągnięciu jest niepoprawny. Czekamy na php-memcached dla PHP 7.1 i będziemy testować dalej.

**Comment by jjuszkiewicz** [comment]
Znaleźliśmy rozwiązanie chodz nie do końca ładne. W php-memcached ustawiliśmy:
```memcached.compression_threshold=9999999999```
i problem przestał występować.
